version: '3.9'

services:
  # database service
  db:
    image: mariadb:10.7
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ~/apps/doscrinium/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: super-secret-pwd
      MYSQL_PASSWORD: secret-pwd
      MYSQL_USER: doscrinium_user
      MYSQL_DATABASE: doscrinium_db

  # storage service
  storage:
    image: minio/minio:latest
    container_name: storage
    command: server /data --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/apps/doscrinium/storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  backend:
    build: 
      context: ./backend
    container_name: backend
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      MYSQL_USER: doscrinium_user
      MYSQL_PASSWORD: secret-pwd
      MINIO_USER: minioadmin
      MINIO_PASSWORD: minioadmin
    volumes:
      - ./backend:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - 3000:80
